/**
 * Blueprint Generator — Sovereign Blueprint Export (v0.9.0)
 *
 * Wraps generated PRD in semantic HTML that acts as an
 * executable context file for AI coding assistants.
 *
 * Note: PRD rendered as raw Markdown in <pre> container.
 * AI agents prefer raw markdown for parsing.
 */

// =============================================================================
// HTML BLUEPRINT GENERATOR
// =============================================================================

export function generateBlueprintHTML(appName: string, generatedPRD: string): string {
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Sovereign Blueprint: ${escapeHtml(appName)}</title>
  <meta name="author" content="The Grove Autonomaton Pattern">
  <meta name="license" content="CC BY 4.0">
  <meta name="generator" content="Grove Foundry v0.9.0">
  <style>
    body { font-family: system-ui, sans-serif; max-width: 900px; margin: 0 auto; padding: 2rem; line-height: 1.6; }
    h1, h2, h3 { font-family: Georgia, serif; }
    code { background: #f4f4f4; padding: 0.2em 0.4em; border-radius: 3px; }
    .warning { background: #fff3cd; border-left: 4px solid #ffc107; padding: 1rem; margin: 1rem 0; }
    .grove-badge { background: #d4621a; color: white; padding: 0.5rem 1rem; display: inline-block; font-family: monospace; }
    .prd-raw { white-space: pre-wrap; font-family: monospace; background: #1a1a1a; color: #e0e0e0; padding: 2rem; overflow-x: auto; }
  </style>
</head>
<body>
  <header>
    <span class="grove-badge">GROVE AUTONOMATON PATTERN</span>
    <h1>Sovereign Blueprint: ${escapeHtml(appName)}</h1>
  </header>

  <section id="grove-philosophy">
    <h2>I. Architectural Philosophy</h2>
    <p>This codebase is governed by the <strong>Grove Autonomaton Pattern</strong>. We separate the cognitive engine from the declarative scaffolding.</p>
    <ul>
      <li><strong>The Pipeline:</strong> Telemetry → Recognition → Compilation → Approval → Execution</li>
      <li><strong>Cognitive Routing:</strong> Route tasks by Tier (0-3) based on complexity and cost</li>
      <li><strong>Sovereignty:</strong> All permissions exist in a declarative schema (Green/Yellow/Red), never hardcoded</li>
    </ul>
  </section>

  <section id="agentic-cursor-rules">
    <h2>II. Agentic Coding Directives</h2>
    <div class="warning">
      <strong>AI CODING ASSISTANT:</strong> You must obey these rules when writing code for this project.
    </div>
    <ol>
      <li>Do not bypass the 5-stage pipeline. Every user interaction flows through all stages.</li>
      <li>Never hardcode API keys or direct LLM calls inside UI components.</li>
      <li>Update <code>zones.schema</code> and <code>routing.config</code> before writing execution code.</li>
      <li>Default risky actions to the Yellow Zone (human approval required).</li>
      <li>Behavior in config, engine logic in code. If a non-technical person can't change it via config, it's wrong.</li>
    </ol>
  </section>

  <section id="project-prd">
    <h2>III. Product Requirements Document</h2>
    <pre class="prd-raw">${escapeHtml(generatedPRD)}</pre>
  </section>

  <footer>
    <p><small>Generated by <a href="https://thegrovefoundation.org">The Grove Foundation</a> • CC BY 4.0</small></p>
  </footer>
</body>
</html>`
}

// =============================================================================
// DOWNLOAD TRIGGER
// =============================================================================

export function downloadBlueprint(appName: string, html: string): void {
  const blob = new Blob([html], { type: 'text/html' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = `sovereign-blueprint-${slugify(appName)}.html`
  a.click()
  URL.revokeObjectURL(url)
}

// =============================================================================
// HELPERS
// =============================================================================

function escapeHtml(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
}

function slugify(str: string): string {
  return str.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '')
}
